export const PRISMA_ERRORS = {
  UNIQUE_CONSTRAINT: "P2002",
  RECORD_NOT_FOUND: "P2025",
  FOREIGN_KEY_CONSTRAINT: "P2003",
  VALUE_TOO_LONG: "P2000",
  VALIDATION_FAILED: "P2007",
  CONNECTION_TIMEOUT: "P1008",
  CANNOT_REACH_DB: "P1001",
} as const;

export type PrismaErrorCode = (typeof PRISMA_ERRORS)[keyof typeof PRISMA_ERRORS];
